03/11/22 (15:30:38) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 954, in _get_key
    with Raw(sys.stdin):
  File "/usr/bin/bpytop", line 798, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
07/11/22 (00:01:15) | ERROR: Data collection thread failed with exception: Precision not allowed in integer format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2771, in _draw_fg
    (f'{proc.details["threads"]:^{iw}.{iw2}}' if expand > 0 else "") + (f'{proc.details["nice"]:^{iw}.{iw2}}' if expand > 1 else "") +
ValueError: Precision not allowed in integer format specifier
07/11/22 (00:01:17) | WARNING: Exiting with errorcode (1). Runtime 0:40:09 

14/12/22 (16:17:25) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
15/12/22 (19:14:01) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
17/12/22 (15:23:00) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
19/12/22 (11:38:54) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
19/12/22 (11:43:20) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
20/12/22 (00:35:04) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
20/12/22 (00:47:54) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
20/12/22 (01:52:18) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
22/12/22 (15:12:55) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
22/12/22 (15:12:58) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
28/12/22 (23:28:37) | ERROR: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.config/bpytop/themes'
